#  ci nivel 1 
name: 'Execucão Manual'

on:
  workflow_dispatch:


jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      
      - uses: actions/checkout@v4

      - name: 'Instalando  dependencias do projeto'
        run: npm install

      - name: 'Rodando o cypress '
        run: npx cypress run 
      
 



