#  ci nivel 1 
name: 'Execucão Manual'

on:
  workflow_dispatch:


jobs:

  unit:
    runs-on: ubuntu-lastest
    timeout-minutes: 60
    steps:
      - name: Rodando Testes Unitario
        run: echo "step unit"


  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit
    timeout-minutes: 60
    steps:
      
      - uses: actions/checkout@v4

      - name: 'Instalando  dependencias do projeto'
        run: npm install

      - name: 'Rodando o cypress '
        run: npx cypress run 
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./cypress/reports



